name: Release
on:
  push:
    tags:
      - "v*.*.*"
env:
  MACOSX_DEPLOYMENT_TARGET: 10.7

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      railway_version: ${{ env.CLI_VERSION }}

    steps:
      - name: Get the release version from the tag
        shell: bash
        if: env.CLI_VERSION == ''
        run: |
          # Apparently, this is the right way to get a tag name. Really?
          #
          # See: https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167/highlight/true#M1027
          echo "CLI_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "version is: ${{ env.CLI_VERSION }}"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.7.0
        with:
          configuration: ".github/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.CLI_VERSION }}
          name: ${{ env.CLI_VERSION }}

  build-release:
    name: Build Release Assets
    needs: ["create-release"]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
            docker-artifact: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross || matrix.os == 'ubuntu-latest' }}

      # Using artifacts to avoid rebuilding cli or fetching from assets section of release page
      - name: Upload docker artifact
        if: ${{ matrix.docker-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-binary-artifact-${{ matrix.target }}
          path: target/${{ matrix.target }}/release

      - name: Store docker artifact version
        if: ${{ matrix.docker-artifact }}
        run: echo "${{ needs.create-release.outputs.railway_version }}" >> cli-version.txt

      - name: Upload docker artifact version
        if: ${{ matrix.docker-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: docker-tag-artifact
          path: cli-version.txt

      - name: Prepare binaries (zip) [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip railway.exe
          7z a ../../../railway-${{ needs.create-release.outputs.railway_version }}-${{ matrix.target }}.zip railway.exe
          cd -

      - name: Prepare binaries (tar) [Windows]
        if: matrix.os == 'windows-latest' || matrix.target == 'i686-pc-windows-gnu'
        run: |
          cd target/${{ matrix.target }}/release
          strip railway.exe
          7z a -ttar archive.tar railway.exe
          7z a -tgzip ../../../railway-${{ needs.create-release.outputs.railway_version }}-${{ matrix.target }}.tar.gz archive.tar
          cd -

      - name: Prepare binaries [-linux]
        if: matrix.os != 'windows-latest' && matrix.target != 'i686-pc-windows-gnu'
        run: |
          cd target/${{ matrix.target }}/release
          strip railway || true
          tar czvf ../../../railway-${{ needs.create-release.outputs.railway_version }}-${{ matrix.target }}.tar.gz railway
          cd -

      - name: Upload release archive
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.create-release.outputs.railway_version }}
          files: railway-${{ needs.create-release.outputs.railway_version }}-${{ matrix.target }}*
